######################################################################
#  Project
######################################################################

BINARY		= main
SRCFILES	= main.c i2c_adc/i2c_adc.c temp_sensor/temp_sensor.c uc_i2c/uc_i2c.c miniprintf/miniprintf.c uc_uart/uc_uart.c uc_timer/uc_timer.c

all: elf bin

include ../../Makefile.incl

# End
