######################################################################
#  Project
######################################################################

BINARY		= main
SRCFILES	= main.c  miniprintf/miniprintf.c system_common/system_common.c uc_timer/uc_timer.c uc_interrupt/uc_interrupt.c dimmer/dimmer.c uc_adc/uc_adc.c temp_sensor/temp_sensor.c uc_uart/uc_uart.c uc_i2c/uc_i2c.c
 
all: elf bin

include ../../Makefile.incl

# End
