######################################################################
#  Project
######################################################################

BINARY		= main
SRCFILES	= main.c i2c_adc/i2c_adc.c  delay/delay.c LCD/LCD.c miniprintf/miniprintf.c system_common/system_common.c uc_timer/uc_timer.c uc_interrupt/uc_interrupt.c dimmer/dimmer.c  temp_sensor/temp_sensor.c uc_uart/uc_uart.c uc_i2c/uc_i2c.c 
 
all: elf bin

include ../../Makefile.incl

# End
